version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .docker_env

  db:
    image: postgres:latest
    env_file: .docker_env
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRESS_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
